<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAZ1D0C3\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAZ1D0C3/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAZ1D0C3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAZ1D0C3\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerAZ1D0C3\srcApp_KernelProdContainer([
    'container.build_hash' => 'AZ1D0C3',
    'container.build_id' => '53fc1a82',
    'container.build_time' => 1582024546,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAZ1D0C3');
